### ISSUE TITLE
potentially improve HTML escaping performance

### ISSUE THREAD

**Issue by gunjam** [gurgunday/ghtml#15]
Hi, I've been comparing HTML escaping performance for a module I'm building and between the implementations within [nunjucks](https://github.com/mozilla/nunjucks/blob/master/nunjucks/src/lib.js#L141-L143), [html-escaper](https://github.com/WebReflection/html-escaper), ghtml and [kitajs](https://github.com/kitajs/html/blob/master/packages/html/index.js#L73-L121) it would appear kita's is the fastest:

```
┌─────────┬────────────────┬─────────┬────────────────────┬──────────┬─────────┐
│ (index) │ Task Name      │ ops/sec │ Average Time (ns)  │ Margin   │ Samples │
├─────────┼────────────────┼─────────┼────────────────────┼──────────┼─────────┤
│ 0       │ 'nunjucks'     │ '1,986' │ 503448.95118268783 │ '±1.19%' │ 1987    │
│ 1       │ 'kitajs'       │ '3,166' │ 315781.80454688927 │ '±0.42%' │ 3167    │
│ 2       │ 'ghtml'        │ '1,906' │ 524471.7005768198  │ '±0.93%' │ 1907    │
│ 3       │ 'html-escaper' │ '2,077' │ 481274.3864292391  │ '±0.86%' │ 2078    │
└─────────┴────────────────┴─────────┴────────────────────┴──────────┴─────────┘
```

Part of the reason kita's implementation is faster is because it does not escape `>`, which apparently isn't needed! I tested the following markup with the [W3 validator](https://validator.w3.org/nu/#textarea) and it passed, so I guess it's true:

```html
<!DOCTYPE html>
<html lang="en-GB">
    <head>
        <title>Title</title>
    </head>
    <body>
        <p class="hello >">
            4 > 2
        </p>
    </body>
</html>
```

Hope this is useful!

<details>

  <summary>Benchmark</summary>

```javascript
import { escape as htmlEscaper } from "html-escaper";
import { Bench } from "tinybench";

/** nunjucks escape
 * @see: https://github.com/mozilla/nunjucks/blob/master/nunjucks/src/lib.js#L141-L143
 */
var escapeMap = {
  "&": "&amp;",
  '"': "&quot;",
  "'": "&#39;",
  "<": "&lt;",
  ">": "&gt;",
  "\\": "&#92;",
};

var escapeRegex = /[&"'<>\\]/g;

function lookupEscape(ch) {
  return escapeMap[ch];
}

function nunjucksEscape(val) {
  return val.replace(escapeRegex, lookupEscape);
}

/** kitajs escape
 * @see: https://github.com/kitajs/html/blob/master/packages/html/index.js#L73-L121
 */
const ESCAPED_REGEX = /[<"'&]/;
const kitaHtml = (value) => {
  if (typeof value !== "string") {
    value = value.toString();
  }

  // This is a optimization to avoid the whole conversion process when the
  // string does not contain any uppercase characters.
  if (!ESCAPED_REGEX.test(value)) {
    return value;
  }

  const length = value.length;

  let escaped = "",
    start = 0,
    end = 0;

  // Escapes double quotes to be used inside attributes
  // Faster than using regex
  // https://jsperf.app/kakihu
  for (; end < length; end++) {
    // https://wonko.com/post/html-escaping
    switch (value[end]) {
      case "&":
        escaped += value.slice(start, end) + "&amp;";
        start = end + 1;
        continue;
      // We don't need to escape > because it is only used to close tags.
      // https://stackoverflow.com/a/9189067
      case "<":
        escaped += value.slice(start, end) + "&lt;";
        start = end + 1;
        continue;
      case '"':
        escaped += value.slice(start, end) + "&#34;";
        start = end + 1;
        continue;
      case "'":
        escaped += value.slice(start, end) + "&#39;";
        start = end + 1;
        continue;
    }
  }

  // Appends the remaining string.
  escaped += value.slice(start, end);

  return escaped;
};

/** ghtml escape
 * @see: https://github.com/kitajs/html/blob/master/packages/html/index.js#L73-L121
 */
const escapeDictionary = {
  '"': "&quot;",
  "'": "&apos;",
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
};

const escapeRegExp = new RegExp(
  `[${Object.keys(escapeDictionary).join("")}]`,
  "gu",
);

const escapeFunction = (key) => {
  return escapeDictionary[key];
};

function ghtmlEscape(val) {
  return val.replace(escapeRegExp, escapeFunction);
}

// Get a big chunk of HTML from GOV.UK
const res = await fetch("https://gov.uk");
const html = await res.text();

const bench = new Bench({ time: 1_000 });

bench
  .add("nunjucks", () => nunjucksEscape(html))
  .add("kitajs", () => kitaHtml(html))
  .add("ghtml", () => ghtmlEscape(html))
  .add("html-escaper", () => htmlEscaper(html));

await bench.warmup();
await bench.run();

console.table(bench.table());

```

</details>

**Comment by gurgunday** [comment]
Hey, thanks for the information and the issue

I will take a look and come back to you about this

**Comment by gurgunday** [comment]
Woah! Kita is truly optimized! I'll shoot a PR soon.

**Comment by gurgunday** [comment]
I was initially impressed by the approach to avoid using regex, but it didn't really improve things when I started benchmarking with significant examples

Regarding the issue of not escaping >, it is dangerous in some cases; we should at the very least escape all HTML characters that have special meanings, including >

Consider this scenario:

```js
const htmlString = html`
  <div
    data-prop=${exp}
  ></div>
`
```

If someone can manipulate exp to include `>`, they can close this tag and gain access to the HTML document; for example, they could do: `><script>alert('pwned')</script>`

**Comment by gunjam** [comment]
Hey thanks for a taking a look at this!

This is a great module btw and I'm currently using it to do a partial port of the [GOV.UK Design System](https://design-system.service.gov.uk/) (nunjucks) as part of some on going experiments I'm doing. Basic idea is to reimplement their nunjucks components as plain JS functions with the same API/param options, for example their [button](https://design-system.service.gov.uk/components/button/):

```nunjucks
{{ govukButton({
  text: "Save and continue"
}) }}
```

I'm getting these numbers for the button implementation:

```
cpu: Apple M1 Pro
runtime: node v22.2.0 (arm64-darwin)

benchmark                         time (avg)             (min … max)       p75       p99      p999
-------------------------------------------------------------------- -----------------------------
govukButton - start now link     302 ns/iter       (274 ns … 446 ns)    308 ns    365 ns    446 ns
govukButton - input              333 ns/iter       (304 ns … 428 ns)    343 ns    393 ns    428 ns
govukButton - button             376 ns/iter       (339 ns … 483 ns)    387 ns    435 ns    483 ns
```

If I hackily replace ghtml's escape code with kita's straight into the node_modules folder, I did get some improvment:

```
cpu: Apple M1 Pro
runtime: node v22.2.0 (arm64-darwin)

benchmark                         time (avg)             (min … max)       p75       p99      p999
-------------------------------------------------------------------- -----------------------------
govukButton - start now link     193 ns/iter       (168 ns … 364 ns)    200 ns    242 ns    323 ns
govukButton - input              199 ns/iter       (183 ns … 256 ns)    208 ns    231 ns    256 ns
govukButton - button             256 ns/iter       (235 ns … 353 ns)    263 ns    294 ns    349 ns
```

Although I appreciate the numbers are still good regardless! 

RE: escaping/not escaping `>`, generally I'd agree with you, as it's something I've always done in the past, however:

> Consider this scenario:
> 
> const htmlString = html`
>   <div
>     data-prop=${exp}
>   ></div>
> `
> 
> If someone can manipulate exp to include >, they can close this tag and gain access to the HTML document; for example, they could do: ><script>alert('pwned')</script>

While in an unquoted attribute unsantisied user input could allow the `<div>` to be closed, it would not allow a `<script>` tag to be opened because the `<` char would be escaped. Your example would output:

```html
    <div
      data-prop=>&lt;script>alert(&#39;pwned&#39;)&lt;/script>
    ></div>
```

Rendering the literal characters to the screen:

> <script>alert('pwned')</script> >

Thanks again!

Hopefully I can find some time to play with it a bit more.

**Comment by gurgunday** [comment]
Very interesting stuff! Thanks!

My realization during experimentation was that if an expression contains escapable characters, the performance is same or slightly worse (we still run a regex and then do the regex-free escaping); if not, it is better

I think you are right because most expressions won't contain those characters; I'll retry over at #16

RE: RE: escaping/not escaping >

Oh yeah, I get it now, I personally always use quotes for attributes anyway, so was trying to generalize, but will take another look at this — so at worse it seems like a tag could be closed early and that could maybe disrupt the document
